name 'puppet-resolv_conf'
version '0.0.2'
dependency 'puppetlabs/stdlib', '>=3.1.0'
summary 'Manage /etc/resolv.conf on Enterprise Linux Servers'
description 'The resolv_conf module configures /etc/resolv.conf on Linux based systems.'
